# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Copy only necessary files
COPY main.py /app

# Install MCP server dependencies
RUN pip install --no-cache-dir "mcp[cli]"

# Expose no ports since stdio server
CMD ["python", "main.py"]
